crds:
  create: false

rbac:
  create: false

serviceAccount:
  create: false

alloy:
  configMap:
    name: "alloy-config"
    content: |
      otelcol.receiver.otlp "default" {
        http {}
        grpc {}

        output {
            metrics = [otelcol.processor.memory_limiter.default.input]
            logs    = [otelcol.processor.memory_limiter.default.input]
            traces  = [otelcol.processor.memory_limiter.default.input]
        }
      }

      otelcol.processor.memory_limiter "default" {
        limit_percentage = 75
        spike_limit_percentage = 10
        check_interval = "2s"

        output {
            metrics = [otelcol.processor.batch.default.input]
            logs    = [otelcol.processor.batch.default.input]
            traces  = [otelcol.processor.batch.default.input]
        }
      }

      otelcol.processor.batch "default" {
        send_batch_max_size = 1000
        send_batch_size = 800

        output {
            metrics = [otelcol.exporter.kafka.default.input]
            logs    = [otelcol.exporter.kafka.default.input]
            traces  = [otelcol.exporter.kafka.default.input]
        }
      }

      otelcol.exporter.kafka "default" {
        brokers          = [sys.env("KAFKA_BROKER")]
        protocol_version = "2.0.0"

        partition_metrics_by_resource_attributes = true
        partition_logs_by_resource_attributes = true
        partition_traces_by_id = true

        metrics {
            topic = "raw-metrics"
            encoding = "otlp_proto"
        }

        logs {
            topic = "raw-logs"
            encoding = "otlp_proto"
        }

        sending_queue {
            enabled = true
            queue_size = 1000
        }

        retry_on_failure {
            enabled = true
            initial_interval = "10s"
            max_interval = "30s"
            max_elapsed_time = "10m"
        }
      }

      // Self-observability configuration
      prometheus.exporter.self "alloy" {}

      prometheus.scrape "alloy_internal" {
        targets    = prometheus.exporter.self.alloy.targets
        forward_to = [prometheus.remote_write.prom.receiver]

        scrape_interval = "30s"
        job_name        = "alloy"
        }

      prometheus.remote_write "prom" {
        endpoint {
            url = "https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push"
            headers = {}
            basic_auth {
                username = sys.env("GC_USERNAME")
                password = sys.env("GC_PASSWORD")
            }
            tls_config {
                insecure_skip_verify = true
            }

            send_native_histograms = false

            queue_config {
              capacity = 10000
              min_shards = 1
              max_shards = 50
              max_samples_per_send = 2000
              batch_send_deadline = "5s"
              min_backoff = "30ms"
              max_backoff = "5s"
              retry_on_http_429 = true
              sample_age_limit = "0s"
            }

          write_relabel_config {
            source_labels = ["cluster"]
            regex = ""
            replacement = "homelab"
            target_label = "cluster"
          }
          write_relabel_config {
            source_labels = ["k8s_cluster_name"]
            regex = ""
            replacement = "homelab"
            target_label = "k8s_cluster_name"
          }
        }
      }
      
  clustering:
    enabled: true
    name: "alloy-cluster"
    portName: http
  stabilityLevel: "public-preview"
  storagePath: /tmp/alloy
  extraEnv: 
    - name: "KAFKA_BROKER"
      value: "homelab-kafka-bootstrap.kafka.svc.cluster.local:9092"
    - name: "GC_USERNAME"
      valueFrom:
        secretKeyRef:
          name: "grafana-cloud-metrics-grafana-k8s-monitoring"
          key: "username"
    - name: "GC_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: "grafana-cloud-metrics-grafana-k8s-monitoring"
          key: "password"
  extraPorts:
    - name: "otlp-grpc"
      port: 4317
      targetPort: 4317
      protocol: "TCP"
    - name: "otlp-http"
      port: 4318
      targetPort: 4318
      protocol: "TCP"
  resources:
    requests:
      memory: "80Mi"
      cpu: "20m"
    limits:
      memory: "256Mi"
      cpu: "200m"

controller:
  type: 'deployment'
  replicas: 1
  podAnnotations:
    reloader.stakater.com/auto: "true"
  autoscaling:
    horizontal:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 0
      targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: true
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd
  labels: {}
  path: /
  faroPort: 12347
  pathType: Prefix
  hosts:
    - alloy.neryolab.com
  tls: []
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: alloy-collector-grpc
      namespace: monitoring
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd
        traefik.ingress.kubernetes.io/service.serversscheme: h2c
    spec:
      ingressClassName: traefik
      rules:
        - host: alloy.neryolab.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: alloy-collector
                    port:
                      number: 4317
      tls:
        - hosts:
            - alloy.neryolab.com
          secretName: alloy-collector-grpc-tls

  - apiVersion: traefik.io/v1alpha1                                                                                                                                   
    kind: Middleware
    metadata:
      name: strip-http
      namespace: monitoring
    spec:
      stripPrefix:
        prefixes:
          - /http

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: alloy-collector-http
      namespace: monitoring
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd,monitoring-strip-http@kubernetescrd
    spec:
      ingressClassName: traefik
      rules:
        - host: alloy.neryolab.com
          http:
            paths:
              - path: /http
                pathType: Prefix
                backend:
                  service:
                    name: alloy-collector
                    port:
                      number: 4318
      tls:
        - hosts:
            - alloy.neryolab.com
          secretName: alloy-collector-http-tls