apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/hhertout/homelab.git
    targetRevision: main
    path: argocd-apps/apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true