apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-user
  annotations:
    policies.kyverno.io/title: Disallow Root User
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Audit
  rules:
    - name: no-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - cert-manager
                - metallb-system
                - monitoring
                - reloader
      validate:
        message: "Running as root is not allowed. Set runAsNonRoot: true."
        pattern:
          spec:
            =(securityContext):
              =(runAsNonRoot): true
