apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.version | default "3.9.2" }}
    metadataVersion: 3.9-IV0
    listeners:
{{ .Values.cluster.listeners | default list | toYaml | indent 6 }}
    config:
      offsets.topic.replication.factor: {{ .Values.cluster.config.topicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.cluster.config.transactionStateLogReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.cluster.config.transactionStateLogMinIsr }}
      default.replication.factor: {{ .Values.cluster.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.cluster.config.minInSyncReplicas }}
  entityOperator:
    topicOperator:
{{ .Values.topicOperator | toYaml | indent 6 }}
    userOperator:
{{ .Values.userOperator | toYaml | indent 6 }}
