apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/hhertout/homelab.git
    path: kafka/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      namespace: kafka
  syncPolicy:
    automated:
      prune: false
      selfHeal: true